// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// Different Errors for the snackbar
export const SNACKBAR_RESET = "SNACKBAR_RESET";
export const ERROR_400 = "ERROR_400";
export const ERROR_401 = "ERROR_401";
export const ERROR_500 = "ERROR_500";
export const ERROR_SOMETHING_ELSE = "ERROR_SOMETHING_ELSE";

// Success for snackbar
export const SUCCESS_200 = "SUCCESS_200";

// Forgot Password
export const FORGOT_PASSWORD_LINK_SENT = "FORGOT_PASSWORD_LINK_SENT";
export const FORGOT_PASSWORD_LINK_RECEIVED = "FORGOT_PASSWORD_LINK_RECEIVED";
export const FORGOT_PASSWORD_LINK_RESET = "FORGOT_PASSWORD_LINK_RESET";
export const SUBMIT_RESET_PASSWORD_TRUE = "SUBMIT_RESET_PASSWORD_TRUE";
export const SUBMIT_RESET_PASSWORD_FALSE = "SUBMIT_RESET_PASSWORD_FALSE";
export const SUBMIT_BUTTON_REST_PASSWORD_FALSE =
  "SUBMIT_BUTTON_REST_PASSWORD_FALSE";
export const SUBMIT_BUTTON_COMPLETE_RESET = "SUBMIT_BUTTON_COMPLETE_RESET";
export const SUBMIT_BUTTON_ERROR_VALID_SECURITY_CODE =
  "SUBMIT_BUTTON_ERROR_VALID_SECURITY_CODE";
export const SUBMIT_BUTTON_ERROR_INVALID_SECURITY_CODE =
  "SUBMIT_BUTTON_ERROR_INVALID_SECURITY_CODE";

// Login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOADING_COMPLETE = "LOGIN_LOADING_COMPLETE";
export const LOGIN_LOADING_ERROR = "LOGIN_LOADING_ERROR";
export const LOGIN_LOADING_ERROR_RESOLVED = "LOGIN_LOADING_ERROR_RESOLVED";

// -------------------- TIMELINE ----------------
export const ADD_ENTRY_TIMELINE = "ADD_ENTRY_TIMELINE";
