// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// Forgot Password
export const SECURITY_CODE_SUCCESS = "SECURITY_CODE_SUCCESS";
export const SECURITY_CODE_LOADING = "SECURITY_CODE_LOADING";
export const SECURITY_CODE_LOADING_COMPLETE = "SECURITY_CODE_LOADING_COMPLETE";

// Display
export const LIGHT_MODE = "LIGHT_MODE";
export const DARK_MODE = "DARK_MODE";

// Reminders 
export const REMINDER_STATUS = "REMINDER_STATUS";
export const REMINDER_ON = "REMINDER_ON";
export const REMINDER_OFF = "REMINDER_OFF";

// Individual Reminders 
export const REMINDER_THREE_HOUR_ON = "REMINDER_THREE_HOUR_ON";
export const REMINDER_TWO_HOUR_ON = "REMINDER_TWO_HOUR_ON";
export const REMINDER_ONE_HOUR_ON = "REMINDER_ONE_HOUR_ON";
export const REMINDER_FIFTEEN_MIN_ON = "REMINDER_FIFTEEN_MIN_ON";
export const REMINDER_THIRTY_MIN_ON = "REMINDER_THIRTY_MIN_ON";
export const REMINDER_THREE_HOUR_OFF = "REMINDER_THREE_HOUR_OFF";
export const REMINDER_TWO_HOUR_OFF = "REMINDER_TWO_HOUR_OFF";
export const REMINDER_ONE_HOUR_OFF = "REMINDER_ONE_HOUR_OFF";
export const REMINDER_FIFTEEN_MIN_OFF = "REMINDER_FIFTEEN_MIN_OFF";
export const REMINDER_THIRTY_MIN_OFF = "REMINDER_THIRTY_MIN_OFF";
export const REMINDER_THIRTY_MIN_STATUS = "REMINDER_THIRTY_MIN_STATUS";
export const REMINDER_FIFTEEN_MIN_STATUS = "REMINDER_FIFTEEN_MIN_STATUS";
export const REMINDER_ONE_HOUR_STATUS = "REMINDER_ONE_HOUR_STATUS";
export const REMINDER_TWO_HOUR_STATUS = "REMINDER_TWO_HOUR_STATUS";
export const REMINDER_THREE_HOUR_STATUS = "REMINDER_THREE_HOUR_STATUS";

// Sound
export const SOUND_STATUS = "SOUND_STATUS";
export const SOUND_ON = "SOUND_ON";
export const SOUND_OFF = "SOUND_OFF";
export const FIFTEEN_MIN_ALERT = "FIFTEEN_MIN_ALERT";
export const THIRTY_MIN_ALERT = "THIRTY_MIN_ALERT";
export const ONE_HOUR_ALERT = "ONE_HOUR_ALERT";
export const TWO_HOUR_ALERT = "TWO_HOUR_ALERT";
export const THREE_HOUR_ALERT = "THREE_HOUR_ALERT";
export const REMINDER_ALERT_RESET = "REMINDER_ALERT_RESET";

// Different Errors for the snackbar
export const SNACKBAR_RESET = "SNACKBAR_RESET";
export const ERROR_SNACKBAR = "ERROR_SNACKBAR";
export const SUCCESS_200 = "SUCCESS_200";
export const ERROR_AUTH_SNACKBAR = "ERROR_AUTH_SNACKBAR";

// Forgot Password
export const FORGOT_PASSWORD_LINK_SENT = "FORGOT_PASSWORD_LINK_SENT";
export const FORGOT_PASSWORD_LINK_RECEIVED = "FORGOT_PASSWORD_LINK_RECEIVED";
export const FORGOT_PASSWORD_LINK_RESET = "FORGOT_PASSWORD_LINK_RESET";
export const SUBMIT_RESET_PASSWORD_TRUE = "SUBMIT_RESET_PASSWORD_TRUE";
export const SUBMIT_RESET_PASSWORD_FALSE = "SUBMIT_RESET_PASSWORD_FALSE";
export const SUBMIT_BUTTON_REST_PASSWORD_FALSE =
  "SUBMIT_BUTTON_REST_PASSWORD_FALSE";
export const SUBMIT_BUTTON_COMPLETE_RESET = "SUBMIT_BUTTON_COMPLETE_RESET";
export const SUBMIT_BUTTON_ERROR_VALID_SECURITY_CODE =
  "SUBMIT_BUTTON_ERROR_VALID_SECURITY_CODE";
export const SUBMIT_BUTTON_ERROR_INVALID_SECURITY_CODE =
  "SUBMIT_BUTTON_ERROR_INVALID_SECURITY_CODE";

// Login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOADING_COMPLETE = "LOGIN_LOADING_COMPLETE";
export const LOGIN_LOADING_ERROR = "LOGIN_LOADING_ERROR";
export const LOGIN_LOADING_ERROR_RESOLVED = "LOGIN_LOADING_ERROR_RESOLVED";

// -------------------- TIMELINE ----------------
export const CREATE_TIMELINE = "CREATE_TIMELINE";
export const ADD_ENTRY_TIMELINE = "ADD_ENTRY_TIMELINE";

export const CREATE_DATES_CAPTURED = "CREATE_DATES_CAPTURED";
export const ADD_DATES_CAPTURED = "ADD_DATES_CAPTURED";

export const LOADING_TIMELINE = "LOADING_TIMELINE";
export const LOADING_TIMELINE_COMPLETE = "LOADING_TIMELINE_COMPLETE";

// ----------------------- NOTES ------------------------------
export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const ADD_NOTE_TITLE = "ADD_NOTE_TITLE";
export const ADD_NOTE_BODY = "ADD_NOTE_BODY";

// -------------------- METRICS ------------------------------
export const TOTAL_COUNT_TUUS = "TOTAL_COUNT_TUUS";
export const TOTAL_COUNT_TUUS_LOADING = "TOTAL_COUNT_TUUS_LOADING";
export const TOTAL_COUNT_TUUS_LOADING_COMPLETE = "TOTAL_COUNT_TUUS_LOADING_COMPLETE";

export const AVG_DURATION_TUUS = "AVG_DURATION_TUUS";
export const AVG_DURATION_TUUS_LOADING = "AVG_DURATION_TUUS_LOADING";
export const AVG_DURATION_TUUS_LOADING_COMPLETE = "AVG_DURATION_TUUS_LOADING_COMPLETE";

export const AVG_DURATION_TUUS_PER_DAY = "AVG_DURATION_TUUS_PER_DAY";
export const AVG_DURATION_TUUS_PER_DAY_LOADING = "AVG_DURATION_TUUS_PER_DAY_LOADING";
export const AVG_DURATION_TUUS_PER_DAY_LOADING_COMPLETE = "AVG_DURATION_TUUS_PER_DAY_LOADING_COMPLETE";
export const AVG_DURATION_TUUS_PER_DAY_HOURS = "AVG_DURATION_TUUS_PER_DAY_HOURS";

export const NUMBER_OF_TUUS = "NUMBER_OF_TUUS";
export const NUMBER_OF_TUUS_LOADING = "NUMBER_OF_TUUS_LOADING";
export const NUMBER_OF_TUUS_LOADING_COMPLETE = "NUMBER_OF_TUUS_LOADING_COMPLETE";

export const LIVE_STREAK = "LIVE_STREAK";
export const LIVE_STREAK_LOADING = "LIVE_STREAK_LOADING";
export const LIVE_STREAK_LOADING_COMPLETE = "LIVE_STREAK_LOADING_COMPLETE";
