export const data = [
  {
    title: "Registration Process",
    details: [
      "Security questions are used if you forget your password.",
      "Always keep the answers to your security questions stored securely.",
    ],
    // imageLight: "https://i.postimg.cc/Wpxc4qNh/register.gif",
    imageLight: "https://i.postimg.cc/TYvKgJqH/ezgif-com-gif-maker.gif",
    imageDark: "https://i.postimg.cc/NjWrHrTL/Animation-Dark.gif",
    tags: ["Security", "Register", "Questions"],
    altImg: "Registration Process Gif",
  },
  {
    title: "Creating a Tuu (Event)",
    details: [
      "Time upto milliseconds is shown for counting",
      "You cannot stop event before 1 minute is completed",
      "Write notes for the corresponding Tuu",
      "Check the timeline after Tuu is completed",
    ],
    imageLight: "https://i.postimg.cc/HWyc3b84/Go-Use-Light.gif",
    imageDark: "https://i.postimg.cc/h4xtFJQ1/Go-Use-Dark.gif",
    tags: ["Gotuu", "Count", "Time"],
    altImg: "Gotuu Process Gif",
  },
  {
    title: "Checking out the timeline",
    details: [
      "Progressively see all events and their corresponding notes",
      "Greater the duration of a Tuu, bigger the circle and darker the color.",
      "Click on the center of the circle to view time in minutes or seconds",
      "Links between Tuus space out if the duration of that event is greater, indicating stretching of the timeline.",
      "Notes have four options - close, completion, edit and delete.",
      "If the tasks of an event given in the note are complete then click on complete. The color of the corresponding link will change from red to light grey.",
      "Tuus are progressively loaded on to the timeline as you scroll",
    ],
    imageLight: "https://i.postimg.cc/QtwjZxWH/Timeline-Light.gif",
    imageDark: "https://i.postimg.cc/mkVNrD7y/Timeline-Dark.gif",
    tags: ["Timeline", "Notes", "Completion"],
    altImg: "Timeline Process Gif",
  },
  {
    title: "Timeline Specifics",
    details: [
      "To change between latest and oldest Tuus, click on the 'chain-link' icon.",
      "Checkout the timeline from other dates by clicking on 'today'",
      "Dates on which Tuus have been recorded are shown in green color.",
      "To minimize the date-picker click on the close icon on it.",
    ],
    imageLight: "https://i.postimg.cc/9XNJDyQq/Timeline-Light-Short.gif",
    imageDark: "https://i.postimg.cc/43PNPfYj/Timeline-Dark-Short.gif",
    tags: ["Timeline", "Notes", "Specifics"],
    altImg: "Timeline Specifics Process Gif",
  },
  {
    title: "Metrics - Graphs",
    details: [
      "'Duration Of Tuus' graph shows the number of mins/hours of Tuus recorded in the given amount of time",
      "Click on the m/h button to change between minutes and hours.",
      "'No. Of Tuus Completed' graph shows the number of Tuus recorded in a given amount of time.",
      "Select between recent seven days, month and year to check metrics of different time periods.",
    ],
    imageLight: "https://i.postimg.cc/d3byFsm4/Metrics-Light.gif",
    imageDark: "https://i.postimg.cc/15xhg8BM/Metrics-Dark.gif",
    tags: ["Timeline", "Notes", "Specifics"],
    altImg: "Timeline Specifics Process Gif",
  },
];